##
## Makefile for Makefile in /home/roye_v/delivery/dante
## 
## Made by Vincent Roye
## Login   <roye_v@epitech.net>
## 
## Started on  Sat May 13 03:35:01 2017 Vincent Roye
## Last update Sat May 13 03:39:41 2017 Vincent Roye
##

all:
	@$(MAKE) -s -C astar/
	@echo -e "compiling : \033[1;29;40mASTAR\033[0m"
	@$(MAKE) -s -C breadth/
	@echo -e "compiling : \033[1;29;40mBREADTH\033[0m"
	@$(MAKE) -s -C depth/
	@echo -e "compiling : \033[1;29;40mDEPTH\033[0m"
	@$(MAKE) -s -C generator/
	@echo -e "compiling : \033[1;29;40mGENERATOR\033[0m"

clean:
	@$(MAKE) clean -s -C astar/
	@echo -e "deleting : \033[1;29;40mASTAR\033[0m"
	@$(MAKE) clean -s -C breadth/
	@echo -e "deleting : \033[1;29;40mBREADTH\033[0m"
	@$(MAKE) clean -s -C depth/
	@echo -e "deleting : \033[1;29;40mDEPTH\033[0m"
	@$(MAKE) clean -s -C generator/
	@echo -e "deleting : \033[1;29;40mGENERATOR\033[0m"

fclean:
	@$(MAKE) fclean -s -C astar/
	@echo -e "removing : \033[1;29;40mASTAR\033[0m"
	@$(MAKE) fclean -s -C breadth/
	@echo -e "removing : \033[1;29;40mBREADTH\033[0m"
	@$(MAKE) fclean -s -C depth/
	@echo -e "removing : \033[1;29;40mDEPTH\033[0m"
	@$(MAKE) fclean -s -C generator/
	@echo -e "removing : \033[1;29;40mGENERATOR\033[0m"

re:
	@$(MAKE) re -s -C astar/
	@echo -e "removing : \033[1;29;40mASTAR\033[0m"
	@echo -e "compiling : \033[1;29;40mASTAR\033[0m"
	@$(MAKE) re -s -C breadth/
	@echo -e "removing : \033[1;29;40mBREADTH\033[0m"
	@echo -e "compiling : \033[1;29;40mBREADTH\033[0m"
	@$(MAKE) re -s -C depth/
	@echo -e "removing : \033[1;29;40mDEPTH\033[0m"
	@echo -e "compiling : \033[1;29;40mDEPTH\033[0m"
	@$(MAKE) re -s -C generator/
	@echo -e "removing : \033[1;29;40mGENERATOR\033[0m"
	@echo -e "compiling : \033[1;29;40mGENERATOR\033[0m"
