#!/bin/bash
clear
trap stop INT
stop() {
    clear
    stty echo
    tput cnorm
    exit
}
rm -f stat
num='^[0-9]+$'
if [[ $# -lt 2 ]] || ! [[ $2 =~ $num ]] || ! [[ -f $1 ]] || [[ $# -gt 3 ]]
then
    echo "Usage : `basename $0` matchstick lines (max)"
    exit
fi
if [[ $# -eq 3 ]] && ! [[ $3 =~ $num ]]
then
    echo "Usage : `basename $0` matchstick lines (max)"
    exit
fi
CT=$(($2+0))
ST=$((2*($CT-1)+1))
if [[ $# -eq 3 ]] && [[ $ST -gt $3 ]]
then
    ST=$3
fi
COL=`tput cols`
ROW=`tput lines`
stty -echo
tput civis
while [[ $R -ne 139 ]]; do
    if [[ $COL -ne `tput cols` ]] || [[ $ROW -ne `tput lines` ]]
    then
        COL=`tput cols`
        ROW=`tput lines`
        clear
    fi
    while [ True ]; do
	echo -e "$(($RANDOM % $(($2 + 1))))\n$(($RANDOM % $(($ST + 1))))";
    done | ./$1 $2 $ST &> /dev/null
    R=`echo $? >> stat`
    AI=`grep "2" stat| wc -l`
    PC=`grep "1" stat| wc -l`
    PER=`echo "($AI * 100) / ($AI + $PC)" | bc`
    TXT="$PER% win of `cat stat | wc -l` games"
    TXT2="RANDOM : $PC - AI: $AI"
    echo -en "\r"
    if [[ $PER -ne 100 ]]; then
	tput cup $(($ROW / 2)) $((($COL - ${#TXT} - 1) / 2))
    else
	tput cup $(($ROW / 2)) $((($COL - ${#TXT}) / 2))
    fi
    echo -en "$TXT\r"
    tput cup $((($ROW / 2)+1)) $((($COL - ${#TXT2}) / 2))
    echo -en "$TXT2"
done
